[package]
name = "fldsmdfr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
zbus = { version = "3", default-features = false, features = ["tokio"]}
